package ar.edu.unlam.dominio;

public enum MenuAscensor {

	ABRIR_PUERTA, INGRESAR, CERRAR_PUERTA, SUBIR, BAJAR, PISO_DESEADO, CONSULTAR_PISO, SALIR_DEL_ASCENSOR, CANTIDAD_DE_PERSONAS_EN_ASCENSOR,FIN; 
}
